services:
  backend:
    command:
      - fastapi
      - run
      - --reload
      - app/main.py
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    volumes:
      - ./backend/htmlcov:/app/backend/htmlcov
    environment:
      SMTP_HOST: mailcatcher
      SMTP_PORT: "1025"
      SMTP_TLS: "false"
      EMAILS_FROM_EMAIL: noreply@example.com

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: http://localhost:8000

  playwright:
    environment:
      VITE_API_URL: http://backend:8000
      MAILCATCHER_HOST: http://mailcatcher:1080
