services:
  db:
    image: postgres:18
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: pepa-linha-dark
    ports:
      - "8080:8080"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    environment:
      FRONTEND_HOST: ${FRONTEND_HOST?Variable not set}
      ENVIRONMENT: ${ENVIRONMENT}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      SECRET_KEY: ${SECRET_KEY?Variable not set}
      FIRST_SUPERUSER: ${FIRST_SUPERUSER?Variable not set}
      FIRST_SUPERUSER_PASSWORD: ${FIRST_SUPERUSER_PASSWORD?Variable not set}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAILS_FROM_EMAIL: ${EMAILS_FROM_EMAIL}
      POSTGRES_SERVER: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      DATABASE_URL: ${DATABASE_URL}
      SENTRY_DSN: ${SENTRY_DSN}
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailcatcher:
    image: schickling/mailcatcher
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: http://localhost:8000
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5173:80"

  playwright:
    build:
      context: .
      dockerfile: frontend/Dockerfile.playwright
      args:
        VITE_API_URL: http://backend:8000
    ipc: host
    depends_on:
      backend:
        condition: service_healthy
      mailcatcher:
        condition: service_started
    env_file:
      - .env
    environment:
      VITE_API_URL: http://backend:8000
      MAILCATCHER_HOST: http://mailcatcher:1080
      PLAYWRIGHT_HTML_HOST: 0.0.0.0
      CI: ${CI}
    volumes:
      - ./frontend/blob-report:/app/frontend/blob-report
      - ./frontend/test-results:/app/frontend/test-results
    ports:
      - "9323:9323"

volumes:
  app-db-data:
